spring:
  datasource:
    username: ${HANGMAN_APP_DB_USERNAME:ivanb}
    url: ${HANGMAN_APP_DB_CONNECTIONSTRING:jdbc:mysql://localhost:3306/hangman-game-db}
    password: ${HANGMAN_APP_DB_PASSWORD:ivanbproxiad}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
cxf:
  path: /soap-services 
shiro:
  loginUrl: /signup
