Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.synced_folder "shared/", "/shared", create: true
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |v|
        v.name = "LabVM"
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
        v.memory = 2048
        v.cpus = 2
      end
      
  end